function I_dJp_F = I_dJp_F_fun(in1,in2)
%I_DJP_F_FUN
%    I_DJP_F = I_DJP_F_FUN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    13-Nov-2019 13:16:07

dq1 = in2(1,:);
dq2 = in2(2,:);
dq3 = in2(3,:);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = q1+q2;
t3 = q1+q2+q3;
t4 = cos(t3);
t5 = t4.*(3.0./2.0e1);
t6 = cos(t2);
t7 = t6.*(7.0./2.5e1);
t8 = sin(t2);
t10 = t8.*(1.0./2.5e1);
t9 = t5+t7-t10;
t11 = sin(t3);
t12 = t11.*(3.0./2.0e1);
t13 = t6.*(1.0./2.5e1);
t14 = t8.*(7.0./2.5e1);
t15 = t12+t13+t14;
t16 = dq1+dq2+dq3;
I_dJp_F = reshape([0.0,-dq1.*(t5+t7-t8.*(1.0./2.5e1)+cos(q1).*(3.0./1.0e1))-dq3.*t4.*(3.0./2.0e1)-dq2.*t9,dq3.*t11.*(-3.0./2.0e1)-dq2.*t15-dq1.*(t12+t13+t14+sin(q1).*(3.0./1.0e1)),0.0,dq3.*t4.*(-3.0./2.0e1)-dq1.*t9-dq2.*t9,dq3.*t11.*(-3.0./2.0e1)-dq1.*t15-dq2.*t15,0.0,t4.*t16.*(-3.0./2.0e1),t11.*t16.*(-3.0./2.0e1)],[3,3]);
