function I_Jp_F = I_Jp_F_fun(in1,in2)
%I_JP_F_FUN
%    I_JP_F = I_JP_F_FUN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    13-Nov-2019 13:16:07

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = q1+q2;
t3 = q1+q2+q3;
t4 = sin(t3);
t5 = cos(t2);
t6 = sin(t2);
t7 = cos(t3);
t8 = t7.*(3.0./2.0e1);
t9 = t5.*(7.0./2.5e1);
I_Jp_F = reshape([0.0,t4.*(-3.0./2.0e1)-t5.*(1.0./2.5e1)-t6.*(7.0./2.5e1)-sin(q1).*(3.0./1.0e1),t6.*(-1.0./2.5e1)+t8+t9+cos(q1).*(3.0./1.0e1),0.0,t4.*(-3.0./2.0e1)-t5.*(1.0./2.5e1)-t6.*(7.0./2.5e1),t6.*(-1.0./2.5e1)+t8+t9,0.0,t4.*(-3.0./2.0e1),t8],[3,3]);
