function I_Jr_F = I_Jr_F_fun(in1,in2)
%I_JR_F_FUN
%    I_JR_F = I_JR_F_FUN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    13-Nov-2019 13:16:07

I_Jr_F = reshape([1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0],[3,3]);
