function out1 = I_r_IF_fun(in1)
%I_R_IF_FUN
%    OUT1 = I_R_IF_FUN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    13-Nov-2019 13:16:06

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = q1+q2;
t3 = q1+q2+q3;
t4 = cos(t2);
t5 = sin(t2);
out1 = [1.0./5.0;t4.*(7.0./2.5e1)-t5.*(1.0./2.5e1)+cos(q1).*(3.0./1.0e1)+cos(t3).*(3.0./2.0e1)+1.0./5.0;t4.*(1.0./2.5e1)+t5.*(7.0./2.5e1)+sin(q1).*(3.0./1.0e1)+sin(t3).*(3.0./2.0e1)+1.0./2.0];
