function I_dJp_F = I_dJp_F_fun(in1,in2)
%I_DJP_F_FUN
%    I_DJP_F = I_DJP_F_FUN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    06-Nov-2019 10:04:08

dq1 = in2(1,:);
dq2 = in2(2,:);
dq3 = in2(3,:);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = q1+q2;
t3 = dq1+dq2+dq3;
t4 = cos(t2);
t5 = q3+t2;
t6 = sin(t2);
t7 = cos(t5);
t8 = sin(t5);
t9 = t4./2.5e+1;
t10 = t4.*(7.0./2.5e+1);
t11 = t6./2.5e+1;
t12 = t6.*(7.0./2.5e+1);
t13 = -t11;
t14 = t7.*(3.0./2.0e+1);
t15 = t8.*(3.0./2.0e+1);
t18 = dq3.*t7.*(-3.0./2.0e+1);
t19 = dq3.*t8.*(-3.0./2.0e+1);
t16 = dq3.*t14;
t17 = dq3.*t15;
t20 = t9+t12+t15;
t21 = t10+t13+t14;
t22 = dq2.*t20;
t23 = dq2.*t21;
t24 = -t22;
t25 = -t23;
I_dJp_F = reshape([0.0,t18+t25-dq1.*(t21+cos(q1).*(3.0./1.0e+1)),t19+t24-dq1.*(t20+sin(q1).*(3.0./1.0e+1)),0.0,t18+t25-dq1.*t21,t19+t24-dq1.*t20,0.0,t3.*t7.*(-3.0./2.0e+1),t3.*t8.*(-3.0./2.0e+1)],[3,3]);
