function I_Jp_F = I_Jp_F_fun(in1,in2)
%I_JP_F_FUN
%    I_JP_F = I_JP_F_FUN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    06-Nov-2019 10:04:08

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = q1+q2;
t3 = cos(t2);
t4 = q3+t2;
t5 = sin(t2);
t6 = cos(t4);
t7 = sin(t4);
t8 = t3./2.5e+1;
t9 = t3.*(7.0./2.5e+1);
t10 = t5./2.5e+1;
t11 = t5.*(7.0./2.5e+1);
t12 = -t8;
t13 = -t10;
t14 = -t11;
t15 = t6.*(3.0./2.0e+1);
t16 = t7.*(3.0./2.0e+1);
t17 = -t16;
I_Jp_F = reshape([0.0,t12+t14+t17-sin(q1).*(3.0./1.0e+1),t9+t13+t15+cos(q1).*(3.0./1.0e+1),0.0,t12+t14+t17,t9+t13+t15,0.0,t17,t15],[3,3]);
